# Generated by Django 4.1.5 on 2023-03-13 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('department', '0012_remove_department_only on draft can be made for each object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redirect_link', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('U', 'user'), ('B', 'broadcast')], max_length=1, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='broadcastNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redirect_link', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('U', 'user'), ('B', 'broadcast')], max_length=1, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_department', to='department.department')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_group', to='auth.group')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usernotifications',
            constraint=models.CheckConstraint(check=models.Q(('type', 'U')), name='only user type'),
        ),
        migrations.AddConstraint(
            model_name='broadcastnotifications',
            constraint=models.CheckConstraint(check=models.Q(('type', 'B')), name='only broadcast type'),
        ),
    ]
