# Generated by Django 4.1.5 on 2023-03-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotifications',
            name='department',
        ),
    ]
