# Generated by Django 4.1.5 on 2023-03-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_broadcastnotifications_department'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='broadcastnotifications',
            name='only broadcast type',
        ),
        migrations.RemoveConstraint(
            model_name='usernotifications',
            name='only user type',
        ),
        migrations.RemoveField(
            model_name='broadcastnotifications',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='type',
        ),
        migrations.AddField(
            model_name='broadcastnotifications',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
