# Generated by Django 4.1.5 on 2023-03-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_broadcastnotifications_only broadcast type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
