# Generated by Django 3.2.18 on 2023-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_department_department'),
        ('student_project', '0002_studentproject_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='department',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='department',
            field=models.ManyToManyField(related_name='studentproject_department', to='department.Department'),
        ),
    ]
