# Generated by Django 3.2.18 on 2023-04-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_department_programs_offered'),
        ('student_project', '0003_auto_20230327_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='studentproject_department', to='department.Department'),
        ),
    ]
