# Generated by Django 3.2.18 on 2023-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_project', '0008_alter_studentproject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
