# Generated by Django 3.2.18 on 2023-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
