# Generated by Django 3.2.18 on 2023-03-22 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_alter_publication_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
