# Generated by Django 3.2.18 on 2023-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_department_department'),
        ('publications', '0003_publication_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='department',
            field=models.ManyToManyField(related_name='publication_department', to='department.Department'),
        ),
    ]
