# Generated by Django 3.2.18 on 2023-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
