# Generated by Django 3.2.18 on 2023-04-21 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publication_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='field_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('SE', 'Software Engineering'), ('NET', 'Networking'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('MATE', 'Materials Engineering'), ('BME', 'Biomedical Engineering'), ('AE', 'Aerospace Engineering'), ('O', 'Other')], default='O', max_length=4), blank=True, null=True, size=None),
        ),
    ]
