# Generated by Django 3.2.18 on 2023-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_publication_field_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
