# Generated by Django 4.1.5 on 2023-03-13 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import research_lab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('draft_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(choices=[('DR', 'Draft'), ('P', 'Pending'), ('A', 'Active'), ('R', 'Rejected')], default='A', max_length=2)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('Head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_head', to=settings.AUTH_USER_MODEL, validators=[research_lab.models.validate_head])),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('allobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='researchlab',
            constraint=models.CheckConstraint(check=models.Q(('is_draft', True), ('is_approved', True), _negated=True), name='research lab draft cannot be approved'),
        ),
        migrations.AddConstraint(
            model_name='researchlab',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved', False), ('is_deleted', False)), fields=('draft_id', 'is_approved', 'is_deleted'), name='research lab Only one draft can be made for each object'),
        ),
        migrations.AddConstraint(
            model_name='researchlab',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code', 'is_approved'), name='research_lab_code_is_unique'),
        ),
    ]
