# Generated by Django 3.2.18 on 2023-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_lab', '0004_researchlab_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='lab_type',
            field=models.CharField(choices=[('UG Lab', 'UG Lab'), ('PG Lab', 'PG Lab'), ('Research Lab', 'Research Lab')], default='UG Lab', max_length=20),
        ),
    ]
