# Generated by Django 3.2.18 on 2023-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_lab', '0005_researchlab_lab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='equipment',
            field=models.TextField(default=''),
        ),
    ]
