# Generated by Django 3.2.18 on 2023-04-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_lab', '0006_researchlab_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchlab',
            old_name='equipment',
            new_name='equipments',
        ),
    ]
