# Generated by Django 3.2.18 on 2023-04-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_department_programs_offered'),
        ('research_lab', '0007_rename_equipment_researchlab_equipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchlab',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='researchlab_department', to='department.Department'),
        ),
    ]
