# Generated by Django 3.2.18 on 2023-04-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_department_programs_offered'),
        ('research_lab', '0008_alter_researchlab_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchlab',
            name='department',
            field=models.ManyToManyField(related_name='researchlab_department', to='department.Department'),
        ),
    ]
