# Generated by Django 3.2.18 on 2023-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_lab', '0011_researchlab_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlab',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
