# Generated by Django 4.1.5 on 2023-03-11 18:10

import department.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Hod', to=settings.AUTH_USER_MODEL, validators=[department.models.validate_hod]),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
