# Generated by Django 4.1.5 on 2023-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
