# Generated by Django 4.1.5 on 2023-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_remove_department_is_approved'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('is_deleted', 'code', 'object_type'), name='department_department_unique_code'),
        ),
    ]
