# Generated by Django 4.1.5 on 2023-03-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_department_department_department_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='department',
            name='draft_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
