# Generated by Django 4.1.5 on 2023-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_remove_department_department_code_is_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='object_type',
            field=models.CharField(choices=[('DR', 'Draft'), ('P', 'Pending'), ('A', 'Active'), ('R', 'Rejected')], default='A', max_length=2),
        ),
    ]
