# Generated by Django 4.1.5 on 2023-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_alter_department_object_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='Only on draft can be made for each object',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved', False), ('is_deleted', False)), fields=('draft_id', 'is_approved', 'is_deleted'), name='Only one draft can be made for each object'),
        ),
    ]
