# Generated by Django 3.2.18 on 2023-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_department_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.ManyToManyField(related_name='department_department', to='department.Department'),
        ),
    ]
