# Generated by Django 3.2.18 on 2023-03-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_department_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='department_code_is_unique',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='department draft cannot be approved',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='department Only one draft can be made for each object',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='draft_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='department',
            name='object_type',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
