# Generated by Django 3.2.18 on 2023-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_auto_20230328_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='programs_offered',
            field=models.TextField(default='BTech CSE, MTech CSE, MTech AI'),
        ),
    ]
