# Generated by Django 3.2.18 on 2023-03-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import staff_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='staffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('Technical Staff', 'Technical Staff'), ('Administrative Staff', 'Administrative Staff')], default='Technical Staff', max_length=20)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to=settings.AUTH_USER_MODEL, validators=[staff_details.models.validate_staff])),
            ],
        ),
    ]
