# Generated by Django 3.2.18 on 2023-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='staff_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='sta_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
