# Generated by Django 3.2.18 on 2023-04-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
