# Generated by Django 3.2.18 on 2023-04-22 09:47

from django.db import migrations, models
import user_queries.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_queries', '0002_alter_querymodel_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=user_queries.models.get_image_name),
        ),
    ]
