# Generated by Django 3.2.18 on 2023-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_queries', '0003_alter_querymodel_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='issue_assigned',
            field=models.CharField(choices=[('Sourabh', 'Sourabh'), ('Sukhmeet', 'Sukhmeet'), ('Vishnu', 'Vishnu'), ('Sumit', 'Sumit'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
