# Generated by Django 4.1.5 on 2023-03-11 11:11

from django.db import migrations
import usercustom.manager


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objectsall', usercustom.manager.UserManager()),
                ('objects', usercustom.manager.UserManagerfiltered()),
            ],
        ),
    ]
