# Generated by Django 4.1.5 on 2023-03-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='get_email_notification',
            field=models.BooleanField(default=True),
        ),
    ]
