# Generated by Django 4.1.5 on 2023-03-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0003_customuser_get_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='get_email_broadcast_notification',
            field=models.BooleanField(default=True),
        ),
    ]
