# Generated by Django 3.2.18 on 2023-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0006_customuser_get_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='get_email_broadcast_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='get_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
