# Generated by Django 3.2.18 on 2023-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0007_auto_20230328_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
