# Generated by Django 3.2.18 on 2023-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0008_customuser_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
