# Generated by Django 3.2.18 on 2023-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0009_customuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctorate_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('fc', 'Faculty'), ('ug', 'ug_student'), ('pg', 'pg_student'), ('phd', 'phd_student'), ('st', 'staff')], default='ug', max_length=5),
        ),
    ]
