# Generated by Django 3.2.18 on 2023-04-27 10:00

from django.db import migrations, models
import usercustom.models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0010_auto_20230420_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=usercustom.models.cover_upload_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=usercustom.models.profile_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='get_email_broadcast_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='get_email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='get_otp_email',
            field=models.BooleanField(default=True),
        ),
    ]
