# Generated by Django 3.2.18 on 2023-05-11 10:20

from django.db import migrations, models
import usercustom.models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0011_auto_20230427_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='upload/profile.png', upload_to=usercustom.models.profile_upload_path),
        ),
    ]
