# Generated by Django 3.2.18 on 2024-04-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0015_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
