# Generated by Django 3.2.18 on 2024-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0017_auto_20240411_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
