# Generated by Django 3.2.18 on 2024-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0019_remove_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
