# Generated by Django 3.2.18 on 2024-04-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0017_alter_customuser_is_active'),
        ('usercustom', '0020_customuser_description'),
    ]

    operations = [
    ]
