# Generated by Django 3.2.18 on 2024-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0021_merge_20240411_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('fc', 'Faculty'), ('ug', 'ug_student'), ('pg', 'pg_student'), ('phd', 'phd_student'), ('st', 'staff'), ('sa', 'super_admin')], default='ug', max_length=5),
        ),
    ]
