# Generated by Django 3.2.18 on 2025-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
    ]
