# Generated by Django 3.2.18 on 2025-03-06 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approve_request', '0002_auto_20250306_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverequest',
            name='achievement_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approverequest',
            name='instructor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approverequest',
            name='applicant_name',
            field=models.CharField(max_length=255),
        ),
    ]
