# Generated by Django 3.2.18 on 2025-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve_request', '0003_auto_20250306_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverequest',
            name='achievement_id',
            field=models.IntegerField(),
        ),
    ]
