# Generated by Django 3.2.18 on 2025-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve_request', '0004_alter_approverequest_achievement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverequest',
            name='achievement_id',
            field=models.IntegerField(default=0),
        ),
    ]
