# Generated by Django 3.2.18 on 2025-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve_request', '0005_alter_approverequest_achievement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverequest',
            name='instructor_id',
            field=models.IntegerField(default=0),
        ),
    ]
