# Generated by Django 3.2.18 on 2023-04-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_participants',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
