# Generated by Django 3.2.18 on 2023-04-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_department_programs_offered'),
        ('events', '0003_event_number_of_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='event_department', to='department.Department'),
        ),
    ]
