# Generated by Django 4.1.5 on 2023-03-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('HC', 'Hackthon'), ('CP', 'Competition'), ('IN', 'Internship'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
