# Generated by Django 3.2.18 on 2023-03-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faculty_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_of_interest', models.TextField(blank=True, null=True)),
                ('phd_instuition', models.TextField(blank=True, null=True)),
                ('faculty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_details', to=settings.AUTH_USER_MODEL, validators=[faculty_details.models.validate_faculty])),
            ],
        ),
    ]
