# Generated by Django 3.2.18 on 2023-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydetails',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facultydetails',
            name='fac_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
