# Generated by Django 3.2.18 on 2023-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_details', '0002_auto_20230402_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='Assistant Professor', max_length=30),
        ),
    ]
