# Generated by Django 3.2.18 on 2023-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reports', '0002_auto_20230421_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogmeetingfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dinfomeetingfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
