# Generated by Django 4.1.5 on 2023-03-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0014_department_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('draft_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(choices=[('DR', 'Draft'), ('P', 'Pending'), ('A', 'Active'), ('R', 'Rejected')], default='A', max_length=2)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('investors', models.TextField(blank=True, null=True)),
                ('amount_invested', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON', 'ONGOING'), ('CO', 'COMPLETED'), ('CA', 'CANCELLED')], default='ON', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_department', to='department.department')),
                ('members', models.ManyToManyField(blank=True, related_name='%(class)s_members', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('allobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('is_draft', True), ('is_approved', True), _negated=True), name='projec draft cannot be approved'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved', False), ('is_deleted', False)), fields=('draft_id', 'is_approved', 'is_deleted'), name='Only one project draft can be made for each object'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code', 'is_approved'), name='project_code_is_unique'),
        ),
    ]
