# Generated by Django 4.1.5 on 2023-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
