# Generated by Django 3.2.18 on 2023-04-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
