# Generated by Django 3.2.18 on 2023-03-22 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_details.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_details', '0003_alter_studentdetails_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='facutly_advisor',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentdetails_faculty_advisor', to=settings.AUTH_USER_MODEL, validators=[student_details.models.validate_faculty_advisor]),
        ),
    ]
