# Generated by Django 3.2.18 on 2023-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0004_auto_20230322_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='department',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'Btech'), ('M.Tech', 'Mtech'), ('Ph.D', 'Phd'), ('M.Sc', 'Msc')], default='B.Tech', max_length=10),
        ),
    ]
