# Generated by Django 3.2.18 on 2023-04-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('student_details', '0005_auto_20230328_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentdetails_batch', to='batch.batch'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='entry_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
